name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Prompt user to select the type of version bump
      - name: Prompt for version bump type
        id: prompt_bump_type
        run: echo "::set-output name=bump_type::$(echo ${{ github.event.inputs.bump_type }} | tr '[:upper:]' '[:lower:]' || echo minor)"
        env:
          DEFAULT_BUMP_TYPE: minor

      # Determine the version bump based on user input
      - name: Determine version bump
        id: version_bump
        run: echo "::set-output name=bump::$(echo ${{ steps.prompt_bump_type.outputs.bump_type }} | tr '[:lower:]' '[:upper:]')"

      # Create a git tag based on the version bump
      - name: Create git tag
        id: create_git_tag
        run: git tag -a "${{ steps.version_bump.outputs.bump }}-$(date +'%Y%m%d%H%M%S')" -m "Release ${{ steps.version_bump.outputs.bump }}-$(date +'%Y%m%d%H%M%S')"
        env:
          GIT_AUTHOR_NAME: ${{ github.actor }}
          GIT_AUTHOR_EMAIL: ${{ github.actor }}@users.noreply.github.com
          GIT_COMMITTER_NAME: ${{ github.actor }}
          GIT_COMMITTER_EMAIL: ${{ github.actor }}@users.noreply.github.com

      # Push the git tag to the repository
      - name: Push git tag
        id: push_git_tag
        uses: EndBug/add-and-commit@v7
        with:
          message: "Added git tag ${{ steps.create_git_tag.outputs.tag }}"
          add: '${{ steps.create_git_tag.outputs.tag }}'
          force: true

      # Deploy to Heroku based on the git tag
      - name: Deploy to Heroku
        id: deploy_to_heroku
        uses: akhileshns/heroku-deploy@v3.12.13
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_APP_EMAIL}}
      - run: echo "Deployed Successfully"
